services:
    php:
        build: .docker/php
        container_name: php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        restart: always

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        restart: always

    db:
        image: mysql:8.1
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql_docker:/var/lib/mysql
            - /var/log/mysql_docker:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: refactorian
            MYSQL_USER: refactorian
            MYSQL_PASSWORD: refactorian
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
        restart: always

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 9090:8080
        depends_on:
            - db
        restart: always

    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --appendonly yes
        volumes:
            - /var/lib/redis_docker:/data
        ports:
            - 6379:6379
        restart: always